Clone the lasted version from Modder

diff --git a/ktweak b/ktweak
--- a/ktweak
+++ b/ktweak
@@ -1,208 +1,307 @@
 #!/system/bin/sh
 # Written by Draco (tytydraco @ GitHub)
 
-# The name of the current branch for logging purposes
-BRANCH="balance"
+# Log in red
+err() {
+	if [[ -n "$SIMPLE_LOGGING" ]]
+	then
+		echo "ERROR $*"
+	else
+		echo -e " \e[91m*\e[39m $*"
+	fi
+}
 
-# Maximum unsigned integer size in C
-UINT_MAX="4294967295"
+# Log in orange
+warn() {
+	if [[ -n "$SIMPLE_LOGGING" ]]
+	then
+		echo "WARNING $*"
+	else
+		echo -e " \e[93m*\e[39m $*"
+	fi
+}
 
-# Duration in nanoseconds of one scheduling period
-SCHED_PERIOD="$((4 * 1000 * 1000))"
+# Log in white and continue (unnecessary)
+dbg() {
+	if [[ -n "$SIMPLE_LOGGING" ]]
+	then
+		echo "DEBUG $*"
+	else
+		echo -e " \e[92m*\e[39m $*"
+	fi
+}
 
-# How many tasks should we have at a maximum in one scheduling period
-SCHED_TASKS="8"
-
+# Safely write value to file
 write() {
 	# Bail out if file does not exist
 	[[ ! -f "$1" ]] && return 1
 
-	# Make file writable in case it is not already
-	chmod +w "$1" 2> /dev/null
+	# Fetch the current key value
+	local curval
+	curval="$(cat "$1" 2> /dev/null)"
 
-	# Write the new value and bail if there's an error
+	# Bail out if value is already set
+	if [[ "$curval" == "$2" ]]
+	then
+		warn "$1: $curval → $2"
+		return 0
+	fi
+
+	# Write the new value
 	if ! echo "$2" > "$1" 2> /dev/null
 	then
-		echo "Failed: $1 → $2"
+		err "$1: $curval → $2"
 		return 1
 	fi
 
-	# Log the success
-	echo "$1 → $2"
+	dbg "$1: $curval → $2"
 }
 
-# Check for root permissions and bail if not granted
+usage() {
+	echo -n "Usage: $(basename "$0") [OPTIONS]
+Options:
+  -p			Parsable logging
+  -h			Show usage
+"
+}
+
+while getopts ":ph" opt; do
+	case $opt in
+		p)
+			SIMPLE_LOGGING=1
+			;;
+		h)
+			usage
+			exit 0
+			;;
+		*)
+			usage
+			exit 1
+			;;
+	esac
+done
+shift $((OPTIND - 1))
+
+# Check for root permissions
 if [[ "$(id -u)" -ne 0 ]]
 then
-	echo "No root permissions. Exiting."
+	err "No root permissions. Exiting."
 	exit 1
 fi
 
-# Detect if we are running on Android
-grep -q android /proc/cmdline && ANDROID=true
 
-# Log the date and time for records sake
-echo "Time of execution: $(date)"
-echo "Branch: $BRANCH"
+# Log the date and time
+dbg "Time of execution: $(date)"
 
-# Sync to data in the rare case a device crashes
-sync
-
-# Limit max perf event processing time to this much CPU usage
+# Kernel
 write /proc/sys/kernel/perf_cpu_time_max_percent 5
-
-# Group tasks for less stutter but less throughput
-write /proc/sys/kernel/sched_autogroup_enabled 1
-
-# Execute child process before parent after fork
+write /proc/sys/kernel/sched_autogroup_enabled 0
 write /proc/sys/kernel/sched_child_runs_first 1
-
-# Preliminary requirement for the following values
 write /proc/sys/kernel/sched_tunable_scaling 0
-
-# Reduce the maximum scheduling period for lower latency
-write /proc/sys/kernel/sched_latency_ns "$SCHED_PERIOD"
-
-# Schedule this ratio of tasks in the guarenteed sched period
-write /proc/sys/kernel/sched_min_granularity_ns "$((SCHED_PERIOD / SCHED_TASKS))"
-
-# Require preeptive tasks to surpass half of a sched period in vmruntime
-write /proc/sys/kernel/sched_wakeup_granularity_ns "$((SCHED_PERIOD / 2))"
-
-# Reduce the frequency of task migrations
+write /proc/sys/kernel/sched_latency_ns 4000000
+write /proc/sys/kernel/sched_min_granularity_ns 200000
+write /proc/sys/kernel/sched_wakeup_granularity_ns 200000
 write /proc/sys/kernel/sched_migration_cost_ns 5000000
-
-# Always allow sched boosting on top-app tasks
-[[ "$ANDROID" == true ]] && write /proc/sys/kernel/sched_min_task_util_for_colocation 0
-
-# Improve real time latencies by reducing the scheduler migration time
-write /proc/sys/kernel/sched_nr_migrate 32
-
-# Disable scheduler statistics to reduce overhead
+write /proc/sys/kernel/sched_min_task_util_for_colocation 0
+write /proc/sys/kernel/sched_nr_migrate 8
 write /proc/sys/kernel/sched_schedstats 0
 
-# Disable unnecessary printk logging
-write /proc/sys/kernel/printk_devkmsg off
-
-# Start non-blocking writeback later
+# VM
 write /proc/sys/vm/dirty_background_ratio 10
-
-# Start blocking writeback later
 write /proc/sys/vm/dirty_ratio 30
-
-# Require dirty memory to stay in memory for longer
 write /proc/sys/vm/dirty_expire_centisecs 3000
-
-# Run the dirty memory flusher threads less often
 write /proc/sys/vm/dirty_writeback_centisecs 3000
-
-# Disable read-ahead for swap devices
 write /proc/sys/vm/page-cluster 0
-
-# Update /proc/stat less often to reduce jitter
+write /proc/sys/vm/reap_mem_on_sigkill 1
 write /proc/sys/vm/stat_interval 10
+write /proc/sys/vm/swappiness 50
+write /proc/sys/vm/overcommit_ratio 30
+write /proc/sys/vm/vfs_cache_pressure 70
 
-# Swap to the swap device at a fair rate
-write /proc/sys/vm/swappiness 100
+# Adreno_Idler 
+write /sys/module/adreno_idler/parameters/adreno_idler_active Y
+write /sys/module/adreno_idler/parameters/adreno_idler_downdifferential 24
+write /sys/module/adreno_idler/parameters/adreno_idler_idlewait 15
+write /sys/module/adreno_idler/parameters/adreno_idler_idleworkload 5000
 
-# Fairly prioritize page cache and file structures
-write /proc/sys/vm/vfs_cache_pressure 100
+# GPU
+write /sys/devices/soc/5000000.qcom,kgsl-3d0/devfreq/5000000.qcom,kgsl-3d0/adrenoboost 3
+write /sys/devices/soc/5000000.qcom,kgsl-3d0/kgsl/kgsl-3d0/throttling 0
 
-# Enable Explicit Congestion Control
-write /proc/sys/net/ipv4/tcp_ecn 1
+# Raid
+write /proc/sys/dev/raid/speed_limit_min 7000
 
-# Enable fast socket open for receiver and sender
-write /proc/sys/net/ipv4/tcp_fastopen 3
+# Pty
+write /proc/sys/kernel/pty/max 4096
 
-# Disable SYN cookies
-write /proc/sys/net/ipv4/tcp_syncookies 0
+# GC_delay
+write /proc/sys/kernel/keys/gc_delay 100
+write /proc/sys/kernel/keys/maxbytes 20000
+write /proc/sys/kernel/keys/maxkeys 200
 
-if [[ -f "/sys/kernel/debug/sched_features" ]]
-then
-	# Consider scheduling tasks that are eager to run
-	write /sys/kernel/debug/sched_features NEXT_BUDDY
+#break_time
+write /proc/sys/fs/lease-break-time 5
+write /proc/sys/fs/leases-enable 1
 
-	# Schedule tasks on their origin CPU if possible
-	write /sys/kernel/debug/sched_features TTWU_QUEUE
-fi
+#sched_domain
+write /proc/sys/kernel/sched_domain/cpu0/domain0/min_interval 2
+write /proc/sys/kernel/sched_domain/cpu0/domain1/min_interval 8
+write /proc/sys/kernel/sched_domain/cpu1/domain0/min_interval 2
+write /proc/sys/kernel/sched_domain/cpu1/domain1/min_interval 8
+write /proc/sys/kernel/sched_domain/cpu2/domain0/min_interval 2
+write /proc/sys/kernel/sched_domain/cpu2/domain1/min_interval 8
+write /proc/sys/kernel/sched_domain/cpu3/domain0/min_interval 2
+write /proc/sys/kernel/sched_domain/cpu3/domain1/min_interval 8
+write /proc/sys/kernel/sched_domain/cpu4/domain0/min_interval 2
+write /proc/sys/kernel/sched_domain/cpu4/domain1/min_interval 8
+write /proc/sys/kernel/sched_domain/cpu5/domain0/min_interval 2
+write /proc/sys/kernel/sched_domain/cpu5/domain1/min_interval 8
+write /proc/sys/kernel/sched_domain/cpu6/domain0/min_interval 2
+write /proc/sys/kernel/sched_domain/cpu6/domain1/min_interval 8
+write /proc/sys/kernel/sched_domain/cpu7/domain0/min_interval 2
+write /proc/sys/kernel/sched_domain/cpu7/domain1/min_interval 8
+write /proc/sys/kernel/sched_domain/cpu0/domain0/busy_factor 32
+write /proc/sys/kernel/sched_domain/cpu1/domain0/busy_factor 32
+write /proc/sys/kernel/sched_domain/cpu2/domain0/busy_factor 32
+write /proc/sys/kernel/sched_domain/cpu3/domain0/busy_factor 32
+write /proc/sys/kernel/sched_domain/cpu4/domain0/busy_factor 32
+write /proc/sys/kernel/sched_domain/cpu5/domain0/busy_factor 32
+write /proc/sys/kernel/sched_domain/cpu6/domain0/busy_factor 32
+write /proc/sys/kernel/sched_domain/cpu7/domain0/busy_factor 32
+write /proc/sys/kernel/sched_domain/cpu0/domain0/busy_idx 2
+write /proc/sys/kernel/sched_domain/cpu1/domain0/busy_idx 2
+write /proc/sys/kernel/sched_domain/cpu2/domain0/busy_idx 2
+write /proc/sys/kernel/sched_domain/cpu3/domain0/busy_idx 2
+write /proc/sys/kernel/sched_domain/cpu4/domain0/busy_idx 2
+write /proc/sys/kernel/sched_domain/cpu5/domain0/busy_idx 2
+write /proc/sys/kernel/sched_domain/cpu6/domain0/busy_idx 2
+write /proc/sys/kernel/sched_domain/cpu7/domain0/busy_idx 2
+write /proc/sys/kernel/sched_domain/cpu0/domain0/cache_nice_tries 1
+write /proc/sys/kernel/sched_domain/cpu1/domain0/cache_nice_tries 1
+write /proc/sys/kernel/sched_domain/cpu2/domain0/cache_nice_tries 1
+write /proc/sys/kernel/sched_domain/cpu3/domain0/cache_nice_tries 1
+write /proc/sys/kernel/sched_domain/cpu4/domain0/cache_nice_tries 1
+write /proc/sys/kernel/sched_domain/cpu5/domain0/cache_nice_tries 1
+write /proc/sys/kernel/sched_domain/cpu6/domain0/cache_nice_tries 1
+write /proc/sys/kernel/sched_domain/cpu7/domain0/cache_nice_tries 1
+write /proc/sys/kernel/sched_domain/cpu0/domain0/flags 4143
+write /proc/sys/kernel/sched_domain/cpu1/domain0/flags 4143
+write /proc/sys/kernel/sched_domain/cpu2/domain0/flags 4143
+write /proc/sys/kernel/sched_domain/cpu3/domain0/flags 4143
+write /proc/sys/kernel/sched_domain/cpu4/domain0/flags 4143
+write /proc/sys/kernel/sched_domain/cpu5/domain0/flags 4143
+write /proc/sys/kernel/sched_domain/cpu6/domain0/flags 4143
+write /proc/sys/kernel/sched_domain/cpu7/domain0/flags 4143
+write /proc/sys/kernel/sched_domain/cpu0/domain0/forkexec_idx 0
+write /proc/sys/kernel/sched_domain/cpu1/domain0/forkexec_idx 0
+write /proc/sys/kernel/sched_domain/cpu2/domain0/forkexec_idx 0
+write /proc/sys/kernel/sched_domain/cpu3/domain0/forkexec_idx 0
+write /proc/sys/kernel/sched_domain/cpu4/domain0/forkexec_idx 0
+write /proc/sys/kernel/sched_domain/cpu5/domain0/forkexec_idx 0
+write /proc/sys/kernel/sched_domain/cpu6/domain0/forkexec_idx 0
+write /proc/sys/kernel/sched_domain/cpu7/domain0/forkexec_idx 0
+write /proc/sys/kernel/sched_domain/cpu0/domain0/idle_idx 1
+write /proc/sys/kernel/sched_domain/cpu1/domain0/idle_idx 1
+write /proc/sys/kernel/sched_domain/cpu2/domain0/idle_idx 1
+write /proc/sys/kernel/sched_domain/cpu3/domain0/idle_idx 1
+write /proc/sys/kernel/sched_domain/cpu4/domain0/idle_idx 1
+write /proc/sys/kernel/sched_domain/cpu5/domain0/idle_idx 1
+write /proc/sys/kernel/sched_domain/cpu6/domain0/idle_idx 1
+write /proc/sys/kernel/sched_domain/cpu7/domain0/idle_idx 1
+write /proc/sys/kernel/sched_domain/cpu0/domain0/imbalance_pct 125
+write /proc/sys/kernel/sched_domain/cpu1/domain0/imbalance_pct 125
+write /proc/sys/kernel/sched_domain/cpu2/domain0/imbalance_pct 125
+write /proc/sys/kernel/sched_domain/cpu3/domain0/imbalance_pct 125
+write /proc/sys/kernel/sched_domain/cpu4/domain0/imbalance_pct 125
+write /proc/sys/kernel/sched_domain/cpu5/domain0/imbalance_pct 125
+write /proc/sys/kernel/sched_domain/cpu6/domain0/imbalance_pct 125
+write /proc/sys/kernel/sched_domain/cpu7/domain0/imbalance_pct 125
+write /proc/sys/kernel/sched_domain/cpu0/domain0/max_interval 4
+write /proc/sys/kernel/sched_domain/cpu1/domain0/max_interval 4
+write /proc/sys/kernel/sched_domain/cpu2/domain0/max_interval 4
+write /proc/sys/kernel/sched_domain/cpu3/domain0/max_interval 4
+write /proc/sys/kernel/sched_domain/cpu4/domain0/max_interval 4
+write /proc/sys/kernel/sched_domain/cpu5/domain0/max_interval 4
+write /proc/sys/kernel/sched_domain/cpu6/domain0/max_interval 4
+write /proc/sys/kernel/sched_domain/cpu7/domain0/max_interval 4
+write /proc/sys/kernel/sched_domain/cpu0/domain0/newidle_idx 0
+write /proc/sys/kernel/sched_domain/cpu1/domain0/newidle_idx 0
+write /proc/sys/kernel/sched_domain/cpu2/domain0/newidle_idx 0
+write /proc/sys/kernel/sched_domain/cpu3/domain0/newidle_idx 0
+write /proc/sys/kernel/sched_domain/cpu4/domain0/newidle_idx 0
+write /proc/sys/kernel/sched_domain/cpu5/domain0/newidle_idx 0
+write /proc/sys/kernel/sched_domain/cpu6/domain0/newidle_idx 0
+write /proc/sys/kernel/sched_domain/cpu7/domain0/newidle_idx 0
+write /proc/sys/kernel/sched_domain/cpu0/domain0/wake_idx 0
+write /proc/sys/kernel/sched_domain/cpu1/domain0/wake_idx 0
+write /proc/sys/kernel/sched_domain/cpu2/domain0/wake_idx 0
+write /proc/sys/kernel/sched_domain/cpu3/domain0/wake_idx 0
+write /proc/sys/kernel/sched_domain/cpu4/domain0/wake_idx 0
+write /proc/sys/kernel/sched_domain/cpu5/domain0/wake_idx 0
+write /proc/sys/kernel/sched_domain/cpu6/domain0/wake_idx 0
+write /proc/sys/kernel/sched_domain/cpu7/domain0/wake_idx 0
 
-[[ "$ANDROID" == true ]] && if [[ -d "/dev/stune/" ]]
-then
-	# We are not concerned with prioritizing latency
-	write /dev/stune/top-app/schedtune.prefer_idle 0
+# Wakeup_threshold
+write /proc/sys/kernel/random/read_wakeup_threshold 16
+write /proc/sys/kernel/random/write_wakeup_threshold 16
+write /proc/sys/kernel/random/urandom_min_reseed_secs 120
 
-	# Mark top-app as boosted, find high-performing CPUs
-	write /dev/stune/top-app/schedtune.boost 1
-fi
+# Stune_Boost
+write /sys/module/cpu_boost/parameters/dynamic_stune_boost 15
+write /sys/module/cpu_boost/parameters/dynamic_stune_boost_ms 500
+write /sys/module/cpu_boost/parameters/input_boost_freq 0:0 1:0 2:0 3:0 4:0 5:0 6:0 7:0 
+write /sys/module/cpu_boost/parameters/input_boost_ms 30
 
-# Loop over each CPU in the system
-for cpu in /sys/devices/system/cpu/cpu*/cpufreq
+# Uclamp
+write /proc/sys/kernel/sched_util_clamp_min 128
+write /proc/sys/kernel/sched_util_clamp_min_rt_default 128
+write /dev/cpuset/top-app/uclamp.max max
+write /dev/cpuset/top-app/uclamp.min 50
+write /dev/cpuset/top-app/uclamp.boosted 1
+write /dev/cpuset/top-app/uclamp.latency_sensitive 1
+write /dev/cpuset/foreground/uclamp.max 50
+write /dev/cpuset/foreground/uclamp.min 20
+write /dev/cpuset/foreground/uclamp.boosted 0
+write /dev/cpuset/foreground/uclamp.latency_sensitive 0
+write /dev/cpuset/background/uclamp.max 50
+write /dev/cpuset/background/uclamp.min 10
+write /dev/cpuset/background/uclamp.boosted 0
+write /dev/cpuset/background/uclamp.latency_sensitive 0
+write /dev/cpuset/system-background/uclamp.max 50
+write /dev/cpuset/system-background/uclamp.min 10
+write /dev/cpuset/system-background/uclamp.boosted 0
+write /dev/cpuset/system-background/uclamp.latency_sensitive 0
+
+# CPU
+for cpu in /sys/devices/system/cpu/cpu*/cpufreq/
 do
-	# Fetch the available governors from the CPU
-	avail_govs="$(cat "$cpu/scaling_available_governors")"
-
-	# Attempt to set the governor in this order
-	for governor in schedutil interactive
-	do
-		# Once a matching governor is found, set it and break for this CPU
-		if [[ "$avail_govs" == *"$governor"* ]]
-		then
-			write "$cpu/scaling_governor" "$governor"
-			break
-		fi
-	done
+	avail_govs="$(cat "${cpu}scaling_available_governors")"
+	if [[ "$avail_govs" == *"schedutil"* ]]
+	then
+		write "${cpu}scaling_governor" schedutil
+		write "${cpu}schedutil/up_rate_limit_us" 0
+		write "${cpu}schedutil/down_rate_limit_us" 0
+		write "${cpu}schedutil/rate_limit_us" 0
+		write "${cpu}schedutil/hispeed_load" 90
+		write "${cpu}schedutil/hispeed_freq" "$(cat "${cpu}cpuinfo_max_freq")"
+	fi
 done
 
-# Apply governor specific tunables for schedutil
-find /sys/devices/system/cpu/ -name schedutil -type d | while IFS= read -r governor
+# I/O
+for queue in /sys/block/*/queue/
 do
-	# Consider changing frequencies once per scheduling period
-	write "$governor/up_rate_limit_us" "$((SCHED_PERIOD / 1000))"
-	write "$governor/down_rate_limit_us" "$((4 * SCHED_PERIOD / 1000))"
-	write "$governor/rate_limit_us" "$((SCHED_PERIOD / 1000))"
-
-	# Jump to hispeed frequency at this load percentage
-	write "$governor/hispeed_load" 90
-	write "$governor/hispeed_freq" "$UINT_MAX"
-done
-
-# Apply governor specific tunables for interactive
-find /sys/devices/system/cpu/ -name interactive -type d | while IFS= read -r governor
-do
-	# Consider changing frequencies once per scheduling period
-	write "$governor/timer_rate" "$((SCHED_PERIOD / 1000))"
-	write "$governor/min_sample_time" "$((SCHED_PERIOD / 1000))"
-
-	# Jump to hispeed frequency at this load percentage
-	write "$governor/go_hispeed_load" 90
-	write "$governor/hispeed_freq" "$UINT_MAX"
-done
-
-for queue in /sys/block/*/queue
-do
-	# Choose the first governor available
-	avail_scheds="$(cat "$queue/scheduler")"
-	for sched in cfq noop kyber bfq mq-deadline none
+	avail_scheds="$(cat "${queue}scheduler")"
+	for sched in cfq anxiety noop kyber bfq mq-deadline none
 	do
 		if [[ "$avail_scheds" == *"$sched"* ]]
 		then
-			write "$queue/scheduler" "$sched"
+			write "${queue}scheduler" "$sched"
 			break
 		fi
 	done
-
-	# Do not use I/O as a source of randomness
-	write "$queue/add_random" 0
-
-	# Disable I/O statistics accounting
-	write "$queue/iostats" 0
-
-	# Reduce heuristic read-ahead in exchange for I/O latency
-	write "$queue/read_ahead_kb" 128
-
-	# Reduce the maximum number of I/O requests in exchange for latency
-	write "$queue/nr_requests" 64
+	write "${queue}iostats" 0
+	write "${queue}read_ahead_kb" 512
+	write "${queue}nr_requests" 128
 done
 
-# Always return success, even if the last write fails
 exit 0
